# Generated by Django 3.1 on 2021-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_snippet_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
